# ------------------------------------------------------------
# English language
# ------------------------------------------------------------
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

# banner
[en.banner]
title = "Support Center & Knowledge base"
subtitle = "Find advice and answers from our support team fast or get in touch"
bg_image = "images/banner.jpg"
placeholder = "Have a question? Just ask here or enter terms"

# call to action
[en.cta]
enable = true
title = "Didn't find an answer to your question?"
content = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."

# call to action button
[en.cta.button]
enable = true
label = "contact us"
link = "contact/"

# ------------------------------------------------------------
# French language
# ------------------------------------------------------------
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2

# banner
[fr.banner]
title = "Comment pouvons nous aider?"
subtitle = "Trouvez rapidement des conseils et des réponses auprès de notre équipe d'assistance ou contactez-nous."
bg_image = "images/banner.jpg"
placeholder = "Avoir une question? Il suffit de demander ici ou de saisir les termes"

# call to action
[fr.cta]
enable = true
title = "Vous n'avez pas trouvé de réponse à votre question?"
content = "Contactez-nous pour plus de détails sur les services supplémentaires et la tarification du travail personnalisé"

# call to action button
[fr.cta.button]
enable = true
label = "Contactez nous"
link = "contact/"